import { diversifyByChapter, estimatedDurationMinutes, recommendExercises, type ExerciseRecommendation } from "@/lib/recommendation";
import { computeChaptersToConsolidate } from "@/lib/next-action";
import type { Chapter } from "@/lib/storage";
import type { Exercise, WorkSession } from "@/lib/supabase/types";

export type PlanIntent = "consolider" | "réviser" | "progresser";
export const PLAN_INTENT_META: Record<PlanIntent, { label: string; description: string }> = { consolider: { label: "Consolider", description: "Ce qui résiste encore" }, réviser: { label: "Réviser", description: "Pour ne pas l'oublier" }, progresser: { label: "Progresser", description: "Un cran au-dessus" } };
export function planIntent(reasons: string[]): PlanIntent { if (reasons.some((r) => r.startsWith("Palier suivant"))) return "progresser"; if (reasons.some((r) => r.startsWith("Non retravaillé depuis") || r === "Maîtrisé, jamais retravaillé")) return "réviser"; return "consolider"; }
export interface PlanBlock { intent: PlanIntent; label: string; focus: string; estimatedMinutes: number; picks: ExerciseRecommendation[]; }
export interface DailyPlan { blocks: PlanBlock[]; requestedMinutes: number; totalMinutes: number; totalExercises: number; }
const INTENT_MIX: { upTo: number; shares: Partial<Record<PlanIntent, number>> }[] = [{ upTo: 29, shares: { consolider: 1 } }, { upTo: 59, shares: { consolider: 0.7, réviser: 0.3 } }, { upTo: 89, shares: { consolider: 0.55, réviser: 0.25, progresser: 0.2 } }, { upTo: Number.POSITIVE_INFINITY, shares: { consolider: 0.45, réviser: 0.25, progresser: 0.3 } }];
function intentSharesFor(totalMinutes: number) { return INTENT_MIX.find((e) => totalMinutes <= e.upTo)!.shares; }
const INTENT_ORDER: PlanIntent[] = ["consolider", "réviser", "progresser"];
function fillBudget(candidates: ExerciseRecommendation[], sessions: WorkSession[], budgetMinutes: number, taken: Set<string>, maxPicks = Number.POSITIVE_INFINITY) { const picks: ExerciseRecommendation[] = []; let remaining = budgetMinutes; for (const candidate of candidates) { if (picks.length >= maxPicks) break; if (taken.has(candidate.exercise.id)) continue; const duration = estimatedDurationMinutes(candidate.exercise, sessions); if (duration > remaining) continue; picks.push(candidate); taken.add(candidate.exercise.id); remaining -= duration; } return { picks, used: budgetMinutes - remaining }; }
function describeFocus(picks: ExerciseRecommendation[], chapterById: Map<string, Chapter>): string { const labels: string[] = []; for (const { exercise } of picks) { const label = (exercise.chapter_id && chapterById.get(exercise.chapter_id)?.label) || exercise.subject; if (!labels.includes(label)) labels.push(label); } if (labels.length <= 2) return labels.join(" · "); return `${labels.slice(0, 2).join(" · ")} +${labels.length - 2}`; }
export function computeDailyPlan(exercises: Exercise[], sessions: WorkSession[], chapters: Chapter[], totalMinutes: number, now: Date = new Date()): DailyPlan { const active=exercises.filter(e=>!e.archived); const chapterById=new Map(chapters.map(c=>[c.id,c])); const empty:DailyPlan={blocks:[],requestedMinutes:totalMinutes,totalMinutes:0,totalExercises:0}; if(totalMinutes<=0||!active.length)return empty; const all=recommendExercises(active,sessions,active.length,{now}); if(!all.length)return empty; const priorityRank=new Map<string,number>(); computeChaptersToConsolidate(exercises,sessions,chapters,now).forEach((e,i)=>priorityRank.set(e.chapter.id,i)); const byIntent=new Map<PlanIntent,ExerciseRecommendation[]>(INTENT_ORDER.map(i=>[i,[]])); for(const r of all)byIntent.get(planIntent(r.reasons))!.push(r); const NO_PRIORITY=Number.MAX_SAFE_INTEGER; const byPriority=[...byIntent.get("consolider")!].sort((a,b)=>(a.exercise.chapter_id?priorityRank.get(a.exercise.chapter_id)??NO_PRIORITY:NO_PRIORITY)-(b.exercise.chapter_id?priorityRank.get(b.exercise.chapter_id)??NO_PRIORITY:NO_PRIORITY)); byIntent.set("consolider",diversifyByChapter(byPriority)); const shares=intentSharesFor(totalMinutes); const taken=new Set<string>(); const blocks:PlanBlock[]=[]; let spent=0; for(const intent of INTENT_ORDER){const share=shares[intent];if(!share)continue;const {picks,used}=fillBudget(byIntent.get(intent)!,sessions,Math.round(totalMinutes*share),taken);if(!picks.length)continue;blocks.push({intent,label:PLAN_INTENT_META[intent].label,focus:describeFocus(picks,chapterById),estimatedMinutes:used,picks});spent+=used;} let leftover=totalMinutes-spent; const addTo=(intent:PlanIntent,budget:number,maxPicks?:number)=>{const {picks,used}=fillBudget(byIntent.get(intent)!,sessions,budget,taken,maxPicks);if(!picks.length)return 0;const existing=blocks.find(b=>b.intent===intent);if(existing){existing.picks.push(...picks);existing.estimatedMinutes+=used;existing.focus=describeFocus(existing.picks,chapterById);}else blocks.push({intent,label:PLAN_INTENT_META[intent].label,focus:describeFocus(picks,chapterById),estimatedMinutes:used,picks});return used;}; for(const intent of INTENT_ORDER){if(leftover<=0)break;if(!shares[intent]||blocks.some(b=>b.intent===intent))continue;leftover-=addTo(intent,leftover,1);} for(const intent of [...blocks].map(b=>b.intent)){if(leftover<=0)break;leftover-=addTo(intent,leftover);} blocks.sort((a,b)=>INTENT_ORDER.indexOf(a.intent)-INTENT_ORDER.indexOf(b.intent)); return {blocks,requestedMinutes:totalMinutes,totalMinutes:blocks.reduce((s,b)=>s+b.estimatedMinutes,0),totalExercises:blocks.reduce((s,b)=>s+b.picks.length,0)}; }
export const PLAN_DURATION_PRESETS=[20,45,60,90] as const; export const DEFAULT_PLAN_MINUTES=45; export const PLAN_STORAGE_KEY="prepahub:plan:pending";
export interface StoredPlanItem { exerciseId:string; reasons:string[]; }
export interface StoredPlan { items:StoredPlanItem[]; requestedMinutes:number; source?:"plan-du-jour"|"libre"|"notion"; label?:string; }
export function resolveStoredPlan(stored:StoredPlan,exercises:Exercise[]):ExerciseRecommendation[]{return stored.items.map(({exerciseId,reasons})=>{const exercise=exercises.find(item=>item.id===exerciseId&&!item.archived);return exercise?{exercise,score:0,reasons}:null;}).filter((item):item is ExerciseRecommendation=>item!==null);}
export function serializePlan(plan:DailyPlan):StoredPlan{return {items:plan.blocks.flatMap(b=>b.picks.map(({exercise,reasons})=>({exerciseId:exercise.id,reasons}))),requestedMinutes:plan.requestedMinutes,source:"plan-du-jour"};}
export function buildFreeSessionPlan(exercises:Exercise[],sessions:WorkSession[],limit:number):StoredPlan{const picked=exercises.slice(0,limit);return {items:picked.map(e=>({exerciseId:e.id,reasons:["Séance libre"]})),requestedMinutes:picked.reduce((s,e)=>s+estimatedDurationMinutes(e,sessions),0),source:"libre"};}
