import { computeNotionEvidence } from "@/lib/notions";
import { computeProgressBySubject, isExerciseEngaged } from "@/lib/progress";
import { recommendExercises, estimatedDurationMinutes } from "@/lib/recommendation";
import { subjects } from "@/lib/study";
import type { Exercise, Subject, WorkSession } from "@/lib/supabase/types";
import type { Chapter } from "@/lib/storage";

export interface PreparationSubjectState { subject: Subject; total: number; mastered: number; completionRate: number; pending: number; minutesToWork: number; lastWorkedAt: string | null; }
export interface PreparationGap { subject: Subject; kind: "jamais commencé" | "délaissée" | "fragile" | "en difficulté"; reason: string; urgency: number; }
export interface PreparationSnapshot { subjects: PreparationSubjectState[]; gaps: PreparationGap[]; testedNotions: number; solidNotions: number; untestedNotions: number; }
export interface PreparationPlanItem { subject: Subject; exerciseId: string; title: string; minutes: number; reason: string; }
export interface PreparationPlan { requestedMinutes: number; allocatedMinutes: number; items: PreparationPlanItem[]; }
function daysSince(value: string | null, now: Date): number | null { if (!value) return null; const time = new Date(value).getTime(); return Number.isNaN(time) ? null : Math.max(0, Math.floor((now.getTime() - time) / 86400000)); }

export function computePreparationSnapshot(exercises: Exercise[], sessions: WorkSession[], chapters: Chapter[], now: Date = new Date()): PreparationSnapshot {
  const progress = computeProgressBySubject(exercises); const active = exercises.filter((e) => !e.archived);
  const states = subjects.map((subject) => { const p = progress.find((x) => x.subject === subject)!; const subjectExercises = active.filter((e) => e.subject === subject); const worked = subjectExercises.filter(isExerciseEngaged); const lastWorkedAt = worked.map((e) => e.last_worked_at).filter((v): v is string => Boolean(v)).sort((a,b) => new Date(b).getTime()-new Date(a).getTime())[0] ?? null; const recommendations = recommendExercises(subjectExercises, sessions, subjectExercises.length, { now }); return { subject, total:p.total, mastered:p.mastered, completionRate:p.completionRate, pending:p.total-p.mastered, minutesToWork:recommendations.reduce((sum,r)=>sum+estimatedDurationMinutes(r.exercise,sessions),0), lastWorkedAt }; }).filter((s)=>s.total>0);
  const gaps = states.map((state) => { const days=daysSince(state.lastWorkedAt,now); if(state.lastWorkedAt===null&&state.pending>0)return {subject:state.subject,kind:"jamais commencé" as const,reason:`${state.pending} exercices non maîtrisés et aucune séance enregistrée`,urgency:3}; if(days!==null&&days>=7&&state.pending>0)return {subject:state.subject,kind:"délaissée" as const,reason:`aucune activité depuis ${days} jours, ${state.pending} exercices restent à travailler`,urgency:2}; if(state.completionRate<50&&state.pending>0)return {subject:state.subject,kind:"en difficulté" as const,reason:`${state.completionRate}% maîtrisé, ${state.pending} exercices restent à travailler`,urgency:2}; if(state.pending>0&&state.completionRate<80)return {subject:state.subject,kind:"fragile" as const,reason:`${state.completionRate}% maîtrisé, ${state.pending} exercices restent à travailler`,urgency:1}; return null; }).filter((g):g is PreparationGap=>g!==null).sort((a,b)=>b.urgency-a.urgency||a.subject.localeCompare(b.subject,"fr"));
  const notionEvidence=computeNotionEvidence(active,sessions); return {subjects:states,gaps,testedNotions:notionEvidence.filter(n=>n.state!=="jamais testée").length,solidNotions:notionEvidence.filter(n=>n.state==="solide").length,untestedNotions:notionEvidence.filter(n=>n.state==="jamais testée").length};
}

export function computePreparationPlan(exercises: Exercise[], sessions: WorkSession[], chapters: Chapter[], totalMinutes: number, now: Date = new Date()): PreparationPlan {
  if(totalMinutes<=0)return {requestedMinutes:totalMinutes,allocatedMinutes:0,items:[]}; const active=exercises.filter(e=>!e.archived); const snapshot=computePreparationSnapshot(active,sessions,chapters,now); const states=snapshot.subjects.filter(s=>s.pending>0); if(!states.length)return {requestedMinutes:totalMinutes,allocatedMinutes:0,items:[]};
  const candidates=new Map<Subject,ReturnType<typeof recommendExercises>>(); for(const state of states){const xs=active.filter(e=>e.subject===state.subject);candidates.set(state.subject,recommendExercises(xs,sessions,xs.length,{now}));}
  const urgency=new Map(snapshot.gaps.map(g=>[g.subject,g.urgency])); const ordered=[...states].sort((a,b)=>(urgency.get(b.subject)??0)-(urgency.get(a.subject)??0)||a.completionRate-b.completionRate||a.subject.localeCompare(b.subject,"fr")); const taken=new Set<string>(); const items:PreparationPlanItem[]=[]; let remaining=totalMinutes;
  for(const state of ordered){const candidate=candidates.get(state.subject)?.find(r=>!taken.has(r.exercise.id)&&estimatedDurationMinutes(r.exercise,sessions)<=remaining); if(!candidate)continue; const minutes=estimatedDurationMinutes(candidate.exercise,sessions); items.push({subject:state.subject,exerciseId:candidate.exercise.id,title:candidate.exercise.title,minutes,reason:candidate.reasons[0]??"À travailler"});taken.add(candidate.exercise.id);remaining-=minutes;}
  for(const candidate of recommendExercises(active,sessions,active.length,{now})){if(taken.has(candidate.exercise.id))continue;const minutes=estimatedDurationMinutes(candidate.exercise,sessions);if(minutes>remaining)continue;items.push({subject:candidate.exercise.subject,exerciseId:candidate.exercise.id,title:candidate.exercise.title,minutes,reason:candidate.reasons[0]??"À travailler"});taken.add(candidate.exercise.id);remaining-=minutes;if(remaining<=0)break;}
  return {requestedMinutes:totalMinutes,allocatedMinutes:totalMinutes-remaining,items};
}
